### ISSUE TITLE
Exiting a new world with bonus chest enabled without saving will result in multiple bonus chest being generated upon reloading 

### ISSUE THREAD

**Issue by JeffDaKilla87** [omo50/Legacy4J-Official-Modpack#1]
![image](https://github.com/omo50/Legacy4J-Official-Modpack/assets/139027212/3f8bd104-8bb5-4dab-8d38-59b800ed6922)

Did this on a superflat world to make easier to see. Does it on regular too, though.

Generate new world with bonus chest enabled > Exit without saving > reload > another chest will spawn

**Comment by omo50** [comment]
This is a Legacy4J issue; not a Re-Console one. Report it to the L4J repo instead
