### ISSUE TITLE
Bugged texture for opened chest.

### ISSUE THREAD

**Issue by Xaaali** [omo50/Legacy4J-Official-Modpack#2]
![2024-05-03_14 26 32_2](https://github.com/omo50/Legacy4J-Official-Modpack/assets/164149081/8b08cf5d-c739-46d1-b5fc-72ffd3f53cd7)

Happens when opening chests, both single and double. Using the normal texture packs already enabled upon download. Happens with the other texture packs as well.

**Comment by Xaaali** [comment]
Adding on to this, it seems to have fixed itself upon reset. I was tinkering around with changing the texture packs before this, so I believe the process of changing them had something to do with it.

**Comment by omo50** [comment]
re-open if it pops up again, thanks
